CREATE DEFINER = CURRENT_USER TRIGGER `poplitic_db`.`POP_USERS_AFTER_INSERT` AFTER INSERT ON `POP_USERS` FOR EACH ROW
BEGIN
    INSERT INTO `poplitic_db`.`POP_USER_PARAMETERS` () VALUES ();
    SET NEW.id_parameter = LAST_INSERT_id();
END